apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: store
  annotations:
    networking.gke.io/max-rate-per-endpoint: "1"
spec:
  selector:
    app: store
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: store
  namespace: store
